name: Build FFmpeg

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  Build_FFmpeg:
    runs-on: windows-2019
    steps:
      - name: Checkout FFmpeg
      - working-directory: C:\
      - uses: actions/checkout@v4
        with:
          repository: FFmpeg/FFmpeg
          ref: release/7.1
          
      - name: Install YASM
        shell: cmd
        run: choco install yasm

      - name: Configure and install FFmpeg
      - working-directory: C:\${{ github.repository }}
        shell: cmd
        run: |
          dir
          ./configure --target-os=win64 --arch=x86_64 --toolchain=msvc --enable-shared --disable-static
          make
          make install
