name: Build FFmpeg

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  configure:
    name: Configure FFmpeg
    runs-on: windows-2019
    steps:
      - name: Checkout FFmpeg repository
      - uses: actions/checkout@v4
        with:
          repository: https://github.com/FFmpeg/FFmpeg.git
          ref: release/7.1
      - shell: cmd
        run: choco install yasm
