name: Build FFmpeg

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

defaults:
  run:
    shell: cmd
  
jobs:
  Build_FFmpeg:
    runs-on: windows-2019
    steps:
      - name: Checkout FFmpeg
      - uses: actions/checkout@v4
        with:
          repository: FFmpeg/FFmpeg
          ref: release/7.1
      
      - name: Install YASM
        run: choco install yasm

      - name: Configure and install FFmpeg
        working-directory: ${{ GITHUB_WORKSPACE }}\${{ github.repository }}
        run: |
          dir
          ./configure --target-os=win64 --arch=x86_64 --toolchain=msvc --enable-shared --disable-static
          make
          make install
