name: Build FFmpeg

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          repository: FFmpeg/FFmpeg
          ref: release/7.1
      - name: Install YASM
        shell: cmd
        run: choco install yasm
