name: Build FFmpeg

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  Build_FFmpeg:
    runs-on: windows-2019
    steps:
      #- name: Checkout FFmpeg
      - uses: actions/checkout@v4
        with:
          repository: FFmpeg/FFmpeg
          ref: release/7.1
          path: ../
      - run: dir
        working-directory: C:\
